/*
 * STX String Functions
 * Copyright (C) 2007-2014 Timo Bingmann <tb@panthema.net>
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <stx-string.h>
#include <set>

#include "strnatcmp.h"
#include "check.h"

void test_static()
{
    CHECK( stx::string::natcmp("120g9el", "99") == 1 );
    CHECK( stx::string::natcmp("8", "665J319048") == -1 );
}

void test_random()
{
    for (unsigned int i = 0; i < 10000; ++i)
    {
        static const char* cset =
            "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
            "01234567890123456789012345678901234567890123456789"
            "01234567890123456789012345678901234567890123456789"
            "     ";

        std::string sa = stx::string::random(rand() % 16, cset);
        std::string sb = stx::string::random(rand() % 16, cset);

        {
            int r1 = stx::string::natcmp(sa, sb);
            int r2 = strnatcmp(sa.c_str(), sb.c_str());

            if (r1 != r2) {
                std::cout << "\n"
                          << "mismatch: \"" << sa << "\" =? \"" << sb << "\"\n"
                          << "r1: " << r1 << " r2: " << r2 << "\n";
            }

            CHECK( r1 == r2 );
        }
        {
            int r1 = stx::string::natcmp_icase(sa, sb);
            int r2 = strnatcasecmp(sa.c_str(), sb.c_str());

            if (r1 != r2) {
                std::cout << "\n"
                          << "mismatch: \"" << sa << "\" =? \"" << sb << "\"\n"
                          << "r1: " << r1 << " r2: " << r2 << "\n";
            }

            CHECK( r1 == r2 );
        }
    }
}

void test_map()
{
    typedef std::set<std::string, stx::string::order_natless> natset_type;
    natset_type natset;

    natset.insert("rfc2086.txt");
    natset.insert("rfc1.txt");
    natset.insert("RFC2.txt");
    natset.insert("rfc822.txt");

    natset_type::const_iterator i = natset.begin();
    CHECK( *i++ == "RFC2.txt" );
    CHECK( *i++ == "rfc1.txt" );
    CHECK( *i++ == "rfc822.txt" );
    CHECK( *i++ == "rfc2086.txt" );
    CHECK( i == natset.end() );

    typedef std::set<std::string, stx::string::order_natless_icase_desc> natset_icase_type;
    natset_icase_type natset_icase(natset.begin(), natset.end());

    natset_icase_type::const_iterator j = natset_icase.begin();
    CHECK( *j++ == "rfc2086.txt" );
    CHECK( *j++ == "rfc822.txt" );
    CHECK( *j++ == "RFC2.txt" );
    CHECK( *j++ == "rfc1.txt" );
    CHECK( j == natset_icase.end() );
}

int main()
{
    test_static();
    test_random();
    test_map();

    return 0;
}
